image: microsoft/dotnet:sdk

pipelines:
  default:
    - step: &buildtest
        name: Build and Unit Test
        caches:
          - dotnetcore
        script:           
          - dotnet restore src -s $NUGET_SOURCE -s https://api.nuget.org/v3/index.json
          - dotnet build src -c Release -p:BuildNumber=$BITBUCKET_BUILD_NUMBER
          - dotnet tool install -g trx2junit
          - export PATH="$PATH:/root/.dotnet/tools"
          - |
                function convert_tests {
                  ls test-results/*.trx | xargs trx2junit
                  rm test-results/*.trx
                }
                trap convert_tests EXIT
          - dotnet vstest src/**/bin/Release/**/**.Tests.dll --logger:trx --ResultsDirectory:test-results            
  branches: 
    master:      
      - step:
          name: Build, Test, Publish NuGet
          caches:
            - dotnetcore
          script:           
            - dotnet restore src -s $NUGET_SOURCE -s https://api.nuget.org/v3/index.json
            - dotnet build src -c Release -p:BuildNumber=$BITBUCKET_BUILD_NUMBER
            - dotnet tool install -g trx2junit
            - export PATH="$PATH:/root/.dotnet/tools"
            - |
                  function convert_tests {
                    ls test-results/*.trx | xargs trx2junit
                    rm test-results/*.trx
                  }
                  trap convert_tests EXIT
            - dotnet vstest src/**/bin/Release/**/**.Tests.dll --logger:trx --ResultsDirectory:test-results   
            - dotnet nuget push src/**/bin/Release/**.nupkg -s $NUGET_SOURCE 