version: 2
jobs:
  build:
    docker:
      - image: dotnet:2.2-sdk
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore src
      - run:
          name: Build
          command: dotnet build src -c Release /p:BuildNumber=${CIRCLE_BUILD_NUM}
      - run:
          name: Pack
          command: dotnet pack src/Provausio.Common/Provausio.Common.csproj
      - run:
          name: Push NuGet packages
          command: dotnet nuget push --source https://api.nuget.org/v3/index.json --api-key ${PROV_NUGET_KEY}